### ISSUE TITLE
work with multiple nodes

### ISSUE THREAD

**Issue by facundoolano** [lambdaclass/throttle#7]
(optionally) share the counts across erlang nodes. Maybe with mnesia

**Comment by unbalancedparentheses** [comment]
options:
- sharding ets (https://github.com/cabol/shards)
- mnesia (easiest)
- riak core (each key has a specific node that manages the data)
- crdts (check lasp)

I think it is a great idea to use a driver strategy and implement a driver for each option. It is a good way of learning more advanced erlang architecture and it will be really interesting to do some benchmark comparison.

**Comment by facundoolano** [comment]
created issues for each multi node driver, closing this one.
